/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ActivityDataAttributes
 */
@JsonPropertyOrder({
  ActivityDataAttributes.JSON_PROPERTY_PROV_COLON_WAS_GENERATED_BY,
  ActivityDataAttributes.JSON_PROPERTY_PROV_COLON_GENERATED_AT_TIME,
  ActivityDataAttributes.JSON_PROPERTY_PROV_COLON_WAS_DERIVED_FROM,
  ActivityDataAttributes.JSON_PROPERTY_PROV_COLON_WAS_ATTRIBUTED_TO,
  ActivityDataAttributes.JSON_PROPERTY_ACTION,
  ActivityDataAttributes.JSON_PROPERTY_VERSION,
  ActivityDataAttributes.JSON_PROPERTY_CHANGES
})

public class ActivityDataAttributes {
  public static final String JSON_PROPERTY_PROV_COLON_WAS_GENERATED_BY = "prov:wasGeneratedBy";
  private String provColonWasGeneratedBy;

  public static final String JSON_PROPERTY_PROV_COLON_GENERATED_AT_TIME = "prov:generatedAtTime";
  private String provColonGeneratedAtTime;

  public static final String JSON_PROPERTY_PROV_COLON_WAS_DERIVED_FROM = "prov:wasDerivedFrom";
  private String provColonWasDerivedFrom;

  public static final String JSON_PROPERTY_PROV_COLON_WAS_ATTRIBUTED_TO = "prov:wasAttributedTo";
  private String provColonWasAttributedTo;

  public static final String JSON_PROPERTY_ACTION = "action";
  private String action;

  public static final String JSON_PROPERTY_VERSION = "version";
  private BigDecimal version;

  public static final String JSON_PROPERTY_CHANGES = "changes";
  private Object changes;


  public ActivityDataAttributes provColonWasGeneratedBy(String provColonWasGeneratedBy) {
    
    this.provColonWasGeneratedBy = provColonWasGeneratedBy;
    return this;
  }

   /**
   * Get provColonWasGeneratedBy
   * @return provColonWasGeneratedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROV_COLON_WAS_GENERATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProvColonWasGeneratedBy() {
    return provColonWasGeneratedBy;
  }


  public void setProvColonWasGeneratedBy(String provColonWasGeneratedBy) {
    this.provColonWasGeneratedBy = provColonWasGeneratedBy;
  }


  public ActivityDataAttributes provColonGeneratedAtTime(String provColonGeneratedAtTime) {
    
    this.provColonGeneratedAtTime = provColonGeneratedAtTime;
    return this;
  }

   /**
   * Get provColonGeneratedAtTime
   * @return provColonGeneratedAtTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROV_COLON_GENERATED_AT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProvColonGeneratedAtTime() {
    return provColonGeneratedAtTime;
  }


  public void setProvColonGeneratedAtTime(String provColonGeneratedAtTime) {
    this.provColonGeneratedAtTime = provColonGeneratedAtTime;
  }


  public ActivityDataAttributes provColonWasDerivedFrom(String provColonWasDerivedFrom) {
    
    this.provColonWasDerivedFrom = provColonWasDerivedFrom;
    return this;
  }

   /**
   * Get provColonWasDerivedFrom
   * @return provColonWasDerivedFrom
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROV_COLON_WAS_DERIVED_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProvColonWasDerivedFrom() {
    return provColonWasDerivedFrom;
  }


  public void setProvColonWasDerivedFrom(String provColonWasDerivedFrom) {
    this.provColonWasDerivedFrom = provColonWasDerivedFrom;
  }


  public ActivityDataAttributes provColonWasAttributedTo(String provColonWasAttributedTo) {
    
    this.provColonWasAttributedTo = provColonWasAttributedTo;
    return this;
  }

   /**
   * Get provColonWasAttributedTo
   * @return provColonWasAttributedTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROV_COLON_WAS_ATTRIBUTED_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProvColonWasAttributedTo() {
    return provColonWasAttributedTo;
  }


  public void setProvColonWasAttributedTo(String provColonWasAttributedTo) {
    this.provColonWasAttributedTo = provColonWasAttributedTo;
  }


  public ActivityDataAttributes action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAction() {
    return action;
  }


  public void setAction(String action) {
    this.action = action;
  }


  public ActivityDataAttributes version(BigDecimal version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getVersion() {
    return version;
  }


  public void setVersion(BigDecimal version) {
    this.version = version;
  }


  public ActivityDataAttributes changes(Object changes) {
    
    this.changes = changes;
    return this;
  }

   /**
   * Get changes
   * @return changes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getChanges() {
    return changes;
  }


  public void setChanges(Object changes) {
    this.changes = changes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityDataAttributes activityDataAttributes = (ActivityDataAttributes) o;
    return Objects.equals(this.provColonWasGeneratedBy, activityDataAttributes.provColonWasGeneratedBy) &&
        Objects.equals(this.provColonGeneratedAtTime, activityDataAttributes.provColonGeneratedAtTime) &&
        Objects.equals(this.provColonWasDerivedFrom, activityDataAttributes.provColonWasDerivedFrom) &&
        Objects.equals(this.provColonWasAttributedTo, activityDataAttributes.provColonWasAttributedTo) &&
        Objects.equals(this.action, activityDataAttributes.action) &&
        Objects.equals(this.version, activityDataAttributes.version) &&
        Objects.equals(this.changes, activityDataAttributes.changes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provColonWasGeneratedBy, provColonGeneratedAtTime, provColonWasDerivedFrom, provColonWasAttributedTo, action, version, changes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityDataAttributes {\n");
    sb.append("    provColonWasGeneratedBy: ").append(toIndentedString(provColonWasGeneratedBy)).append("\n");
    sb.append("    provColonGeneratedAtTime: ").append(toIndentedString(provColonGeneratedAtTime)).append("\n");
    sb.append("    provColonWasDerivedFrom: ").append(toIndentedString(provColonWasDerivedFrom)).append("\n");
    sb.append("    provColonWasAttributedTo: ").append(toIndentedString(provColonWasAttributedTo)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

