/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributesDescriptions
 */
@JsonPropertyOrder({
  DoiDataAttributesDescriptions.JSON_PROPERTY_DESCRIPTION,
  DoiDataAttributesDescriptions.JSON_PROPERTY_DESCRIPTION_TYPE,
  DoiDataAttributesDescriptions.JSON_PROPERTY_LANG
})

public class DoiDataAttributesDescriptions {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_DESCRIPTION_TYPE = "descriptionType";
  private String descriptionType;

  public static final String JSON_PROPERTY_LANG = "lang";
  private String lang;


  public DoiDataAttributesDescriptions description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public DoiDataAttributesDescriptions descriptionType(String descriptionType) {
    
    this.descriptionType = descriptionType;
    return this;
  }

   /**
   * Get descriptionType
   * @return descriptionType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescriptionType() {
    return descriptionType;
  }


  public void setDescriptionType(String descriptionType) {
    this.descriptionType = descriptionType;
  }


  public DoiDataAttributesDescriptions lang(String lang) {
    
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LANG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLang() {
    return lang;
  }


  public void setLang(String lang) {
    this.lang = lang;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesDescriptions doiDataAttributesDescriptions = (DoiDataAttributesDescriptions) o;
    return Objects.equals(this.description, doiDataAttributesDescriptions.description) &&
        Objects.equals(this.descriptionType, doiDataAttributesDescriptions.descriptionType) &&
        Objects.equals(this.lang, doiDataAttributesDescriptions.lang);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, descriptionType, lang);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesDescriptions {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    descriptionType: ").append(toIndentedString(descriptionType)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

