/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Data describing the landing page, used by link checking.
 */
@ApiModel(description = "Data describing the landing page, used by link checking.")
@JsonPropertyOrder({
  DoiDataAttributesLandingPage.JSON_PROPERTY_CHECKED,
  DoiDataAttributesLandingPage.JSON_PROPERTY_URL,
  DoiDataAttributesLandingPage.JSON_PROPERTY_CONTENT_TYPE,
  DoiDataAttributesLandingPage.JSON_PROPERTY_ERROR,
  DoiDataAttributesLandingPage.JSON_PROPERTY_REDIRECT_COUNT,
  DoiDataAttributesLandingPage.JSON_PROPERTY_REDIRECT_URLS,
  DoiDataAttributesLandingPage.JSON_PROPERTY_DOWNLOAD_LATENCY,
  DoiDataAttributesLandingPage.JSON_PROPERTY_HAS_SCHEMA_ORG,
  DoiDataAttributesLandingPage.JSON_PROPERTY_SCHEMA_ORGID,
  DoiDataAttributesLandingPage.JSON_PROPERTY_DC_IDENTIFIER,
  DoiDataAttributesLandingPage.JSON_PROPERTY_CITATION_DOI,
  DoiDataAttributesLandingPage.JSON_PROPERTY_BODYHAS_PID
})

public class DoiDataAttributesLandingPage {
  public static final String JSON_PROPERTY_CHECKED = "checked";
  private String checked;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_CONTENT_TYPE = "contentType";
  private String contentType;

  public static final String JSON_PROPERTY_ERROR = "error";
  private String error;

  public static final String JSON_PROPERTY_REDIRECT_COUNT = "redirectCount";
  private BigDecimal redirectCount;

  public static final String JSON_PROPERTY_REDIRECT_URLS = "redirectUrls";
  private List<String> redirectUrls = null;

  public static final String JSON_PROPERTY_DOWNLOAD_LATENCY = "downloadLatency";
  private BigDecimal downloadLatency;

  public static final String JSON_PROPERTY_HAS_SCHEMA_ORG = "hasSchemaOrg";
  private Boolean hasSchemaOrg;

  public static final String JSON_PROPERTY_SCHEMA_ORGID = "schemaOrgid";
  private String schemaOrgid;

  public static final String JSON_PROPERTY_DC_IDENTIFIER = "dcIdentifier";
  private String dcIdentifier;

  public static final String JSON_PROPERTY_CITATION_DOI = "citationDoi";
  private String citationDoi;

  public static final String JSON_PROPERTY_BODYHAS_PID = "bodyhasPid";
  private Boolean bodyhasPid;


  public DoiDataAttributesLandingPage checked(String checked) {
    
    this.checked = checked;
    return this;
  }

   /**
   * Get checked
   * @return checked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHECKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChecked() {
    return checked;
  }


  public void setChecked(String checked) {
    this.checked = checked;
  }


  public DoiDataAttributesLandingPage url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public DoiDataAttributesLandingPage contentType(String contentType) {
    
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContentType() {
    return contentType;
  }


  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  public DoiDataAttributesLandingPage error(String error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getError() {
    return error;
  }


  public void setError(String error) {
    this.error = error;
  }


  public DoiDataAttributesLandingPage redirectCount(BigDecimal redirectCount) {
    
    this.redirectCount = redirectCount;
    return this;
  }

   /**
   * Get redirectCount
   * @return redirectCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REDIRECT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRedirectCount() {
    return redirectCount;
  }


  public void setRedirectCount(BigDecimal redirectCount) {
    this.redirectCount = redirectCount;
  }


  public DoiDataAttributesLandingPage redirectUrls(List<String> redirectUrls) {
    
    this.redirectUrls = redirectUrls;
    return this;
  }

  public DoiDataAttributesLandingPage addRedirectUrlsItem(String redirectUrlsItem) {
    if (this.redirectUrls == null) {
      this.redirectUrls = new ArrayList<>();
    }
    this.redirectUrls.add(redirectUrlsItem);
    return this;
  }

   /**
   * Get redirectUrls
   * @return redirectUrls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REDIRECT_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRedirectUrls() {
    return redirectUrls;
  }


  public void setRedirectUrls(List<String> redirectUrls) {
    this.redirectUrls = redirectUrls;
  }


  public DoiDataAttributesLandingPage downloadLatency(BigDecimal downloadLatency) {
    
    this.downloadLatency = downloadLatency;
    return this;
  }

   /**
   * Get downloadLatency
   * @return downloadLatency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DOWNLOAD_LATENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDownloadLatency() {
    return downloadLatency;
  }


  public void setDownloadLatency(BigDecimal downloadLatency) {
    this.downloadLatency = downloadLatency;
  }


  public DoiDataAttributesLandingPage hasSchemaOrg(Boolean hasSchemaOrg) {
    
    this.hasSchemaOrg = hasSchemaOrg;
    return this;
  }

   /**
   * Get hasSchemaOrg
   * @return hasSchemaOrg
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HAS_SCHEMA_ORG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasSchemaOrg() {
    return hasSchemaOrg;
  }


  public void setHasSchemaOrg(Boolean hasSchemaOrg) {
    this.hasSchemaOrg = hasSchemaOrg;
  }


  public DoiDataAttributesLandingPage schemaOrgid(String schemaOrgid) {
    
    this.schemaOrgid = schemaOrgid;
    return this;
  }

   /**
   * Get schemaOrgid
   * @return schemaOrgid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA_ORGID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaOrgid() {
    return schemaOrgid;
  }


  public void setSchemaOrgid(String schemaOrgid) {
    this.schemaOrgid = schemaOrgid;
  }


  public DoiDataAttributesLandingPage dcIdentifier(String dcIdentifier) {
    
    this.dcIdentifier = dcIdentifier;
    return this;
  }

   /**
   * Get dcIdentifier
   * @return dcIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DC_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDcIdentifier() {
    return dcIdentifier;
  }


  public void setDcIdentifier(String dcIdentifier) {
    this.dcIdentifier = dcIdentifier;
  }


  public DoiDataAttributesLandingPage citationDoi(String citationDoi) {
    
    this.citationDoi = citationDoi;
    return this;
  }

   /**
   * Get citationDoi
   * @return citationDoi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CITATION_DOI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCitationDoi() {
    return citationDoi;
  }


  public void setCitationDoi(String citationDoi) {
    this.citationDoi = citationDoi;
  }


  public DoiDataAttributesLandingPage bodyhasPid(Boolean bodyhasPid) {
    
    this.bodyhasPid = bodyhasPid;
    return this;
  }

   /**
   * Get bodyhasPid
   * @return bodyhasPid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BODYHAS_PID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBodyhasPid() {
    return bodyhasPid;
  }


  public void setBodyhasPid(Boolean bodyhasPid) {
    this.bodyhasPid = bodyhasPid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesLandingPage doiDataAttributesLandingPage = (DoiDataAttributesLandingPage) o;
    return Objects.equals(this.checked, doiDataAttributesLandingPage.checked) &&
        Objects.equals(this.url, doiDataAttributesLandingPage.url) &&
        Objects.equals(this.contentType, doiDataAttributesLandingPage.contentType) &&
        Objects.equals(this.error, doiDataAttributesLandingPage.error) &&
        Objects.equals(this.redirectCount, doiDataAttributesLandingPage.redirectCount) &&
        Objects.equals(this.redirectUrls, doiDataAttributesLandingPage.redirectUrls) &&
        Objects.equals(this.downloadLatency, doiDataAttributesLandingPage.downloadLatency) &&
        Objects.equals(this.hasSchemaOrg, doiDataAttributesLandingPage.hasSchemaOrg) &&
        Objects.equals(this.schemaOrgid, doiDataAttributesLandingPage.schemaOrgid) &&
        Objects.equals(this.dcIdentifier, doiDataAttributesLandingPage.dcIdentifier) &&
        Objects.equals(this.citationDoi, doiDataAttributesLandingPage.citationDoi) &&
        Objects.equals(this.bodyhasPid, doiDataAttributesLandingPage.bodyhasPid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checked, url, contentType, error, redirectCount, redirectUrls, downloadLatency, hasSchemaOrg, schemaOrgid, dcIdentifier, citationDoi, bodyhasPid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesLandingPage {\n");
    sb.append("    checked: ").append(toIndentedString(checked)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    redirectCount: ").append(toIndentedString(redirectCount)).append("\n");
    sb.append("    redirectUrls: ").append(toIndentedString(redirectUrls)).append("\n");
    sb.append("    downloadLatency: ").append(toIndentedString(downloadLatency)).append("\n");
    sb.append("    hasSchemaOrg: ").append(toIndentedString(hasSchemaOrg)).append("\n");
    sb.append("    schemaOrgid: ").append(toIndentedString(schemaOrgid)).append("\n");
    sb.append("    dcIdentifier: ").append(toIndentedString(dcIdentifier)).append("\n");
    sb.append("    citationDoi: ").append(toIndentedString(citationDoi)).append("\n");
    sb.append("    bodyhasPid: ").append(toIndentedString(bodyhasPid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

