/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributesRightsList
 */
@JsonPropertyOrder({
  DoiDataAttributesRightsList.JSON_PROPERTY_RIGHTS,
  DoiDataAttributesRightsList.JSON_PROPERTY_RIGHTS_URI,
  DoiDataAttributesRightsList.JSON_PROPERTY_LANG
})

public class DoiDataAttributesRightsList {
  public static final String JSON_PROPERTY_RIGHTS = "rights";
  private String rights;

  public static final String JSON_PROPERTY_RIGHTS_URI = "rightsUri";
  private String rightsUri;

  public static final String JSON_PROPERTY_LANG = "lang";
  private String lang;


  public DoiDataAttributesRightsList rights(String rights) {
    
    this.rights = rights;
    return this;
  }

   /**
   * Get rights
   * @return rights
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RIGHTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRights() {
    return rights;
  }


  public void setRights(String rights) {
    this.rights = rights;
  }


  public DoiDataAttributesRightsList rightsUri(String rightsUri) {
    
    this.rightsUri = rightsUri;
    return this;
  }

   /**
   * Get rightsUri
   * @return rightsUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RIGHTS_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRightsUri() {
    return rightsUri;
  }


  public void setRightsUri(String rightsUri) {
    this.rightsUri = rightsUri;
  }


  public DoiDataAttributesRightsList lang(String lang) {
    
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LANG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLang() {
    return lang;
  }


  public void setLang(String lang) {
    this.lang = lang;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesRightsList doiDataAttributesRightsList = (DoiDataAttributesRightsList) o;
    return Objects.equals(this.rights, doiDataAttributesRightsList.rights) &&
        Objects.equals(this.rightsUri, doiDataAttributesRightsList.rightsUri) &&
        Objects.equals(this.lang, doiDataAttributesRightsList.lang);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rights, rightsUri, lang);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesRightsList {\n");
    sb.append("    rights: ").append(toIndentedString(rights)).append("\n");
    sb.append("    rightsUri: ").append(toIndentedString(rightsUri)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

