/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributesFundingReferences
 */
@JsonPropertyOrder({
  DoiDataAttributesFundingReferences.JSON_PROPERTY_FUNDER_NAME,
  DoiDataAttributesFundingReferences.JSON_PROPERTY_FUNDER_IDENTIFIER,
  DoiDataAttributesFundingReferences.JSON_PROPERTY_FUNDER_IDENTIFIER_TYPE,
  DoiDataAttributesFundingReferences.JSON_PROPERTY_AWARD_NUMBER,
  DoiDataAttributesFundingReferences.JSON_PROPERTY_AWARD_URI,
  DoiDataAttributesFundingReferences.JSON_PROPERTY_AWARD_TITLE
})

public class DoiDataAttributesFundingReferences {
  public static final String JSON_PROPERTY_FUNDER_NAME = "funderName";
  private String funderName;

  public static final String JSON_PROPERTY_FUNDER_IDENTIFIER = "funderIdentifier";
  private String funderIdentifier;

  public static final String JSON_PROPERTY_FUNDER_IDENTIFIER_TYPE = "funderIdentifierType";
  private String funderIdentifierType;

  public static final String JSON_PROPERTY_AWARD_NUMBER = "awardNumber";
  private String awardNumber;

  public static final String JSON_PROPERTY_AWARD_URI = "awardUri";
  private String awardUri;

  public static final String JSON_PROPERTY_AWARD_TITLE = "awardTitle";
  private String awardTitle;


  public DoiDataAttributesFundingReferences funderName(String funderName) {
    
    this.funderName = funderName;
    return this;
  }

   /**
   * Get funderName
   * @return funderName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FUNDER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunderName() {
    return funderName;
  }


  public void setFunderName(String funderName) {
    this.funderName = funderName;
  }


  public DoiDataAttributesFundingReferences funderIdentifier(String funderIdentifier) {
    
    this.funderIdentifier = funderIdentifier;
    return this;
  }

   /**
   * Get funderIdentifier
   * @return funderIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FUNDER_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunderIdentifier() {
    return funderIdentifier;
  }


  public void setFunderIdentifier(String funderIdentifier) {
    this.funderIdentifier = funderIdentifier;
  }


  public DoiDataAttributesFundingReferences funderIdentifierType(String funderIdentifierType) {
    
    this.funderIdentifierType = funderIdentifierType;
    return this;
  }

   /**
   * Get funderIdentifierType
   * @return funderIdentifierType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FUNDER_IDENTIFIER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunderIdentifierType() {
    return funderIdentifierType;
  }


  public void setFunderIdentifierType(String funderIdentifierType) {
    this.funderIdentifierType = funderIdentifierType;
  }


  public DoiDataAttributesFundingReferences awardNumber(String awardNumber) {
    
    this.awardNumber = awardNumber;
    return this;
  }

   /**
   * Get awardNumber
   * @return awardNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AWARD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAwardNumber() {
    return awardNumber;
  }


  public void setAwardNumber(String awardNumber) {
    this.awardNumber = awardNumber;
  }


  public DoiDataAttributesFundingReferences awardUri(String awardUri) {
    
    this.awardUri = awardUri;
    return this;
  }

   /**
   * Get awardUri
   * @return awardUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AWARD_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAwardUri() {
    return awardUri;
  }


  public void setAwardUri(String awardUri) {
    this.awardUri = awardUri;
  }


  public DoiDataAttributesFundingReferences awardTitle(String awardTitle) {
    
    this.awardTitle = awardTitle;
    return this;
  }

   /**
   * Get awardTitle
   * @return awardTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AWARD_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAwardTitle() {
    return awardTitle;
  }


  public void setAwardTitle(String awardTitle) {
    this.awardTitle = awardTitle;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesFundingReferences doiDataAttributesFundingReferences = (DoiDataAttributesFundingReferences) o;
    return Objects.equals(this.funderName, doiDataAttributesFundingReferences.funderName) &&
        Objects.equals(this.funderIdentifier, doiDataAttributesFundingReferences.funderIdentifier) &&
        Objects.equals(this.funderIdentifierType, doiDataAttributesFundingReferences.funderIdentifierType) &&
        Objects.equals(this.awardNumber, doiDataAttributesFundingReferences.awardNumber) &&
        Objects.equals(this.awardUri, doiDataAttributesFundingReferences.awardUri) &&
        Objects.equals(this.awardTitle, doiDataAttributesFundingReferences.awardTitle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(funderName, funderIdentifier, funderIdentifierType, awardNumber, awardUri, awardTitle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesFundingReferences {\n");
    sb.append("    funderName: ").append(toIndentedString(funderName)).append("\n");
    sb.append("    funderIdentifier: ").append(toIndentedString(funderIdentifier)).append("\n");
    sb.append("    funderIdentifierType: ").append(toIndentedString(funderIdentifierType)).append("\n");
    sb.append("    awardNumber: ").append(toIndentedString(awardNumber)).append("\n");
    sb.append("    awardUri: ").append(toIndentedString(awardUri)).append("\n");
    sb.append("    awardTitle: ").append(toIndentedString(awardTitle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

