/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributesAffiliation
 */
@JsonPropertyOrder({
  DoiDataAttributesAffiliation.JSON_PROPERTY_NAME,
  DoiDataAttributesAffiliation.JSON_PROPERTY_AFFILIATION_IDENTIFIER,
  DoiDataAttributesAffiliation.JSON_PROPERTY_AFFILIATION_IDENTIFIER_SCHEME,
  DoiDataAttributesAffiliation.JSON_PROPERTY_SCHEME_URI
})

public class DoiDataAttributesAffiliation {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_AFFILIATION_IDENTIFIER = "affiliationIdentifier";
  private String affiliationIdentifier;

  public static final String JSON_PROPERTY_AFFILIATION_IDENTIFIER_SCHEME = "affiliationIdentifierScheme";
  private String affiliationIdentifierScheme;

  public static final String JSON_PROPERTY_SCHEME_URI = "schemeUri";
  private String schemeUri;


  public DoiDataAttributesAffiliation name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DoiDataAttributesAffiliation affiliationIdentifier(String affiliationIdentifier) {
    
    this.affiliationIdentifier = affiliationIdentifier;
    return this;
  }

   /**
   * Get affiliationIdentifier
   * @return affiliationIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AFFILIATION_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAffiliationIdentifier() {
    return affiliationIdentifier;
  }


  public void setAffiliationIdentifier(String affiliationIdentifier) {
    this.affiliationIdentifier = affiliationIdentifier;
  }


  public DoiDataAttributesAffiliation affiliationIdentifierScheme(String affiliationIdentifierScheme) {
    
    this.affiliationIdentifierScheme = affiliationIdentifierScheme;
    return this;
  }

   /**
   * Get affiliationIdentifierScheme
   * @return affiliationIdentifierScheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AFFILIATION_IDENTIFIER_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAffiliationIdentifierScheme() {
    return affiliationIdentifierScheme;
  }


  public void setAffiliationIdentifierScheme(String affiliationIdentifierScheme) {
    this.affiliationIdentifierScheme = affiliationIdentifierScheme;
  }


  public DoiDataAttributesAffiliation schemeUri(String schemeUri) {
    
    this.schemeUri = schemeUri;
    return this;
  }

   /**
   * Get schemeUri
   * @return schemeUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEME_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemeUri() {
    return schemeUri;
  }


  public void setSchemeUri(String schemeUri) {
    this.schemeUri = schemeUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesAffiliation doiDataAttributesAffiliation = (DoiDataAttributesAffiliation) o;
    return Objects.equals(this.name, doiDataAttributesAffiliation.name) &&
        Objects.equals(this.affiliationIdentifier, doiDataAttributesAffiliation.affiliationIdentifier) &&
        Objects.equals(this.affiliationIdentifierScheme, doiDataAttributesAffiliation.affiliationIdentifierScheme) &&
        Objects.equals(this.schemeUri, doiDataAttributesAffiliation.schemeUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, affiliationIdentifier, affiliationIdentifierScheme, schemeUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesAffiliation {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    affiliationIdentifier: ").append(toIndentedString(affiliationIdentifier)).append("\n");
    sb.append("    affiliationIdentifierScheme: ").append(toIndentedString(affiliationIdentifierScheme)).append("\n");
    sb.append("    schemeUri: ").append(toIndentedString(schemeUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

