/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributesNameIdentifiers
 */
@JsonPropertyOrder({
  DoiDataAttributesNameIdentifiers.JSON_PROPERTY_NAME_IDENTIFIER,
  DoiDataAttributesNameIdentifiers.JSON_PROPERTY_NAME_IDENTIFIER_SCHEME,
  DoiDataAttributesNameIdentifiers.JSON_PROPERTY_SCHEME_URI
})

public class DoiDataAttributesNameIdentifiers {
  public static final String JSON_PROPERTY_NAME_IDENTIFIER = "nameIdentifier";
  private String nameIdentifier;

  public static final String JSON_PROPERTY_NAME_IDENTIFIER_SCHEME = "nameIdentifierScheme";
  private String nameIdentifierScheme;

  public static final String JSON_PROPERTY_SCHEME_URI = "schemeUri";
  private String schemeUri;


  public DoiDataAttributesNameIdentifiers nameIdentifier(String nameIdentifier) {
    
    this.nameIdentifier = nameIdentifier;
    return this;
  }

   /**
   * Get nameIdentifier
   * @return nameIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameIdentifier() {
    return nameIdentifier;
  }


  public void setNameIdentifier(String nameIdentifier) {
    this.nameIdentifier = nameIdentifier;
  }


  public DoiDataAttributesNameIdentifiers nameIdentifierScheme(String nameIdentifierScheme) {
    
    this.nameIdentifierScheme = nameIdentifierScheme;
    return this;
  }

   /**
   * Get nameIdentifierScheme
   * @return nameIdentifierScheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_IDENTIFIER_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameIdentifierScheme() {
    return nameIdentifierScheme;
  }


  public void setNameIdentifierScheme(String nameIdentifierScheme) {
    this.nameIdentifierScheme = nameIdentifierScheme;
  }


  public DoiDataAttributesNameIdentifiers schemeUri(String schemeUri) {
    
    this.schemeUri = schemeUri;
    return this;
  }

   /**
   * Get schemeUri
   * @return schemeUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEME_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemeUri() {
    return schemeUri;
  }


  public void setSchemeUri(String schemeUri) {
    this.schemeUri = schemeUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesNameIdentifiers doiDataAttributesNameIdentifiers = (DoiDataAttributesNameIdentifiers) o;
    return Objects.equals(this.nameIdentifier, doiDataAttributesNameIdentifiers.nameIdentifier) &&
        Objects.equals(this.nameIdentifierScheme, doiDataAttributesNameIdentifiers.nameIdentifierScheme) &&
        Objects.equals(this.schemeUri, doiDataAttributesNameIdentifiers.schemeUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameIdentifier, nameIdentifierScheme, schemeUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesNameIdentifiers {\n");
    sb.append("    nameIdentifier: ").append(toIndentedString(nameIdentifier)).append("\n");
    sb.append("    nameIdentifierScheme: ").append(toIndentedString(nameIdentifierScheme)).append("\n");
    sb.append("    schemeUri: ").append(toIndentedString(schemeUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

