/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributesSubjects
 */
@JsonPropertyOrder({
  DoiDataAttributesSubjects.JSON_PROPERTY_SUBJECT,
  DoiDataAttributesSubjects.JSON_PROPERTY_SUBJECT_SCHEME,
  DoiDataAttributesSubjects.JSON_PROPERTY_SCHEME_URI,
  DoiDataAttributesSubjects.JSON_PROPERTY_VALUE_URI,
  DoiDataAttributesSubjects.JSON_PROPERTY_LANG
})

public class DoiDataAttributesSubjects {
  public static final String JSON_PROPERTY_SUBJECT = "subject";
  private String subject;

  public static final String JSON_PROPERTY_SUBJECT_SCHEME = "subjectScheme";
  private String subjectScheme;

  public static final String JSON_PROPERTY_SCHEME_URI = "schemeUri";
  private String schemeUri;

  public static final String JSON_PROPERTY_VALUE_URI = "valueUri";
  private String valueUri;

  public static final String JSON_PROPERTY_LANG = "lang";
  private String lang;


  public DoiDataAttributesSubjects subject(String subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubject() {
    return subject;
  }


  public void setSubject(String subject) {
    this.subject = subject;
  }


  public DoiDataAttributesSubjects subjectScheme(String subjectScheme) {
    
    this.subjectScheme = subjectScheme;
    return this;
  }

   /**
   * Get subjectScheme
   * @return subjectScheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECT_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubjectScheme() {
    return subjectScheme;
  }


  public void setSubjectScheme(String subjectScheme) {
    this.subjectScheme = subjectScheme;
  }


  public DoiDataAttributesSubjects schemeUri(String schemeUri) {
    
    this.schemeUri = schemeUri;
    return this;
  }

   /**
   * Get schemeUri
   * @return schemeUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEME_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemeUri() {
    return schemeUri;
  }


  public void setSchemeUri(String schemeUri) {
    this.schemeUri = schemeUri;
  }


  public DoiDataAttributesSubjects valueUri(String valueUri) {
    
    this.valueUri = valueUri;
    return this;
  }

   /**
   * Get valueUri
   * @return valueUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALUE_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueUri() {
    return valueUri;
  }


  public void setValueUri(String valueUri) {
    this.valueUri = valueUri;
  }


  public DoiDataAttributesSubjects lang(String lang) {
    
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LANG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLang() {
    return lang;
  }


  public void setLang(String lang) {
    this.lang = lang;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesSubjects doiDataAttributesSubjects = (DoiDataAttributesSubjects) o;
    return Objects.equals(this.subject, doiDataAttributesSubjects.subject) &&
        Objects.equals(this.subjectScheme, doiDataAttributesSubjects.subjectScheme) &&
        Objects.equals(this.schemeUri, doiDataAttributesSubjects.schemeUri) &&
        Objects.equals(this.valueUri, doiDataAttributesSubjects.valueUri) &&
        Objects.equals(this.lang, doiDataAttributesSubjects.lang);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, subjectScheme, schemeUri, valueUri, lang);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesSubjects {\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    subjectScheme: ").append(toIndentedString(subjectScheme)).append("\n");
    sb.append("    schemeUri: ").append(toIndentedString(schemeUri)).append("\n");
    sb.append("    valueUri: ").append(toIndentedString(valueUri)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

