/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributesRelatedIdentifiers
 */
@JsonPropertyOrder({
  DoiDataAttributesRelatedIdentifiers.JSON_PROPERTY_RELATED_IDENTIFIER,
  DoiDataAttributesRelatedIdentifiers.JSON_PROPERTY_RELATED_IDENTIFIER_TYPE,
  DoiDataAttributesRelatedIdentifiers.JSON_PROPERTY_RELATION_TYPE,
  DoiDataAttributesRelatedIdentifiers.JSON_PROPERTY_RESOURCE_TYPE_GENERAL
})

public class DoiDataAttributesRelatedIdentifiers {
  public static final String JSON_PROPERTY_RELATED_IDENTIFIER = "relatedIdentifier";
  private String relatedIdentifier;

  public static final String JSON_PROPERTY_RELATED_IDENTIFIER_TYPE = "relatedIdentifierType";
  private String relatedIdentifierType;

  public static final String JSON_PROPERTY_RELATION_TYPE = "relationType";
  private String relationType;

  public static final String JSON_PROPERTY_RESOURCE_TYPE_GENERAL = "resourceTypeGeneral";
  private String resourceTypeGeneral;


  public DoiDataAttributesRelatedIdentifiers relatedIdentifier(String relatedIdentifier) {
    
    this.relatedIdentifier = relatedIdentifier;
    return this;
  }

   /**
   * Get relatedIdentifier
   * @return relatedIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELATED_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelatedIdentifier() {
    return relatedIdentifier;
  }


  public void setRelatedIdentifier(String relatedIdentifier) {
    this.relatedIdentifier = relatedIdentifier;
  }


  public DoiDataAttributesRelatedIdentifiers relatedIdentifierType(String relatedIdentifierType) {
    
    this.relatedIdentifierType = relatedIdentifierType;
    return this;
  }

   /**
   * Get relatedIdentifierType
   * @return relatedIdentifierType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELATED_IDENTIFIER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelatedIdentifierType() {
    return relatedIdentifierType;
  }


  public void setRelatedIdentifierType(String relatedIdentifierType) {
    this.relatedIdentifierType = relatedIdentifierType;
  }


  public DoiDataAttributesRelatedIdentifiers relationType(String relationType) {
    
    this.relationType = relationType;
    return this;
  }

   /**
   * Get relationType
   * @return relationType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelationType() {
    return relationType;
  }


  public void setRelationType(String relationType) {
    this.relationType = relationType;
  }


  public DoiDataAttributesRelatedIdentifiers resourceTypeGeneral(String resourceTypeGeneral) {
    
    this.resourceTypeGeneral = resourceTypeGeneral;
    return this;
  }

   /**
   * Get resourceTypeGeneral
   * @return resourceTypeGeneral
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESOURCE_TYPE_GENERAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResourceTypeGeneral() {
    return resourceTypeGeneral;
  }


  public void setResourceTypeGeneral(String resourceTypeGeneral) {
    this.resourceTypeGeneral = resourceTypeGeneral;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesRelatedIdentifiers doiDataAttributesRelatedIdentifiers = (DoiDataAttributesRelatedIdentifiers) o;
    return Objects.equals(this.relatedIdentifier, doiDataAttributesRelatedIdentifiers.relatedIdentifier) &&
        Objects.equals(this.relatedIdentifierType, doiDataAttributesRelatedIdentifiers.relatedIdentifierType) &&
        Objects.equals(this.relationType, doiDataAttributesRelatedIdentifiers.relationType) &&
        Objects.equals(this.resourceTypeGeneral, doiDataAttributesRelatedIdentifiers.resourceTypeGeneral);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relatedIdentifier, relatedIdentifierType, relationType, resourceTypeGeneral);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesRelatedIdentifiers {\n");
    sb.append("    relatedIdentifier: ").append(toIndentedString(relatedIdentifier)).append("\n");
    sb.append("    relatedIdentifierType: ").append(toIndentedString(relatedIdentifierType)).append("\n");
    sb.append("    relationType: ").append(toIndentedString(relationType)).append("\n");
    sb.append("    resourceTypeGeneral: ").append(toIndentedString(resourceTypeGeneral)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

