/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesAffiliation;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesNameIdentifiers;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributesCreators
 */
@JsonPropertyOrder({
  DoiDataAttributesCreators.JSON_PROPERTY_NAME_TYPE,
  DoiDataAttributesCreators.JSON_PROPERTY_NAME_IDENTIFIERS,
  DoiDataAttributesCreators.JSON_PROPERTY_NAME,
  DoiDataAttributesCreators.JSON_PROPERTY_GIVEN_NAME,
  DoiDataAttributesCreators.JSON_PROPERTY_FAMILY_NAME,
  DoiDataAttributesCreators.JSON_PROPERTY_AFFILIATION
})

public class DoiDataAttributesCreators {
  public static final String JSON_PROPERTY_NAME_TYPE = "nameType";
  private String nameType;

  public static final String JSON_PROPERTY_NAME_IDENTIFIERS = "nameIdentifiers";
  private List<DoiDataAttributesNameIdentifiers> nameIdentifiers = null;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_GIVEN_NAME = "givenName";
  private String givenName;

  public static final String JSON_PROPERTY_FAMILY_NAME = "familyName";
  private String familyName;

  public static final String JSON_PROPERTY_AFFILIATION = "affiliation";
  private List<DoiDataAttributesAffiliation> affiliation = null;


  public DoiDataAttributesCreators nameType(String nameType) {
    
    this.nameType = nameType;
    return this;
  }

   /**
   * Get nameType
   * @return nameType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameType() {
    return nameType;
  }


  public void setNameType(String nameType) {
    this.nameType = nameType;
  }


  public DoiDataAttributesCreators nameIdentifiers(List<DoiDataAttributesNameIdentifiers> nameIdentifiers) {
    
    this.nameIdentifiers = nameIdentifiers;
    return this;
  }

  public DoiDataAttributesCreators addNameIdentifiersItem(DoiDataAttributesNameIdentifiers nameIdentifiersItem) {
    if (this.nameIdentifiers == null) {
      this.nameIdentifiers = new ArrayList<>();
    }
    this.nameIdentifiers.add(nameIdentifiersItem);
    return this;
  }

   /**
   * Get nameIdentifiers
   * @return nameIdentifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesNameIdentifiers> getNameIdentifiers() {
    return nameIdentifiers;
  }


  public void setNameIdentifiers(List<DoiDataAttributesNameIdentifiers> nameIdentifiers) {
    this.nameIdentifiers = nameIdentifiers;
  }


  public DoiDataAttributesCreators name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DoiDataAttributesCreators givenName(String givenName) {
    
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GIVEN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGivenName() {
    return givenName;
  }


  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }


  public DoiDataAttributesCreators familyName(String familyName) {
    
    this.familyName = familyName;
    return this;
  }

   /**
   * Get familyName
   * @return familyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFamilyName() {
    return familyName;
  }


  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }


  public DoiDataAttributesCreators affiliation(List<DoiDataAttributesAffiliation> affiliation) {
    
    this.affiliation = affiliation;
    return this;
  }

  public DoiDataAttributesCreators addAffiliationItem(DoiDataAttributesAffiliation affiliationItem) {
    if (this.affiliation == null) {
      this.affiliation = new ArrayList<>();
    }
    this.affiliation.add(affiliationItem);
    return this;
  }

   /**
   * Get affiliation
   * @return affiliation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AFFILIATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesAffiliation> getAffiliation() {
    return affiliation;
  }


  public void setAffiliation(List<DoiDataAttributesAffiliation> affiliation) {
    this.affiliation = affiliation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributesCreators doiDataAttributesCreators = (DoiDataAttributesCreators) o;
    return Objects.equals(this.nameType, doiDataAttributesCreators.nameType) &&
        Objects.equals(this.nameIdentifiers, doiDataAttributesCreators.nameIdentifiers) &&
        Objects.equals(this.name, doiDataAttributesCreators.name) &&
        Objects.equals(this.givenName, doiDataAttributesCreators.givenName) &&
        Objects.equals(this.familyName, doiDataAttributesCreators.familyName) &&
        Objects.equals(this.affiliation, doiDataAttributesCreators.affiliation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameType, nameIdentifiers, name, givenName, familyName, affiliation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributesCreators {\n");
    sb.append("    nameType: ").append(toIndentedString(nameType)).append("\n");
    sb.append("    nameIdentifiers: ").append(toIndentedString(nameIdentifiers)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    affiliation: ").append(toIndentedString(affiliation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

