/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesContainer;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesContributors;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesCreators;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesDates;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesDescriptions;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesFundingReferences;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesGeoLocations;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesIdentifiers;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesLandingPage;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesRelatedIdentifiers;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesRightsList;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesSubjects;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesTitles;
import no.unit.nva.doi.datacite.client.model.DoiDataAttributesTypes;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DoiDataAttributes
 */
@JsonPropertyOrder({
  DoiDataAttributes.JSON_PROPERTY_DOI,
  DoiDataAttributes.JSON_PROPERTY_PREFIX,
  DoiDataAttributes.JSON_PROPERTY_SUFFIX,
  DoiDataAttributes.JSON_PROPERTY_EVENT,
  DoiDataAttributes.JSON_PROPERTY_IDENTIFIERS,
  DoiDataAttributes.JSON_PROPERTY_CREATORS,
  DoiDataAttributes.JSON_PROPERTY_TITLES,
  DoiDataAttributes.JSON_PROPERTY_PUBLISHER,
  DoiDataAttributes.JSON_PROPERTY_CONTAINER,
  DoiDataAttributes.JSON_PROPERTY_PUBLICATION_YEAR,
  DoiDataAttributes.JSON_PROPERTY_SUBJECTS,
  DoiDataAttributes.JSON_PROPERTY_CONTRIBUTORS,
  DoiDataAttributes.JSON_PROPERTY_DATES,
  DoiDataAttributes.JSON_PROPERTY_LANGUAGE,
  DoiDataAttributes.JSON_PROPERTY_TYPES,
  DoiDataAttributes.JSON_PROPERTY_RELATED_IDENTIFIERS,
  DoiDataAttributes.JSON_PROPERTY_SIZES,
  DoiDataAttributes.JSON_PROPERTY_FORMATS,
  DoiDataAttributes.JSON_PROPERTY_VERSION,
  DoiDataAttributes.JSON_PROPERTY_RIGHTS_LIST,
  DoiDataAttributes.JSON_PROPERTY_DESCRIPTIONS,
  DoiDataAttributes.JSON_PROPERTY_GEO_LOCATIONS,
  DoiDataAttributes.JSON_PROPERTY_FUNDING_REFERENCES,
  DoiDataAttributes.JSON_PROPERTY_URL,
  DoiDataAttributes.JSON_PROPERTY_CONTENT_URL,
  DoiDataAttributes.JSON_PROPERTY_METADATA_VERSION,
  DoiDataAttributes.JSON_PROPERTY_SCHEMA_VERSION,
  DoiDataAttributes.JSON_PROPERTY_SOURCE,
  DoiDataAttributes.JSON_PROPERTY_IS_ACTIVE,
  DoiDataAttributes.JSON_PROPERTY_STATE,
  DoiDataAttributes.JSON_PROPERTY_REASON,
  DoiDataAttributes.JSON_PROPERTY_LANDING_PAGE,
  DoiDataAttributes.JSON_PROPERTY_CREATED,
  DoiDataAttributes.JSON_PROPERTY_REGISTERED,
  DoiDataAttributes.JSON_PROPERTY_UPDATED
})

public class DoiDataAttributes {
  public static final String JSON_PROPERTY_DOI = "doi";
  private String doi;

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  private String prefix;

  public static final String JSON_PROPERTY_SUFFIX = "suffix";
  private String suffix;

  /**
   * Can be set to trigger a DOI state change.
   */
  public enum EventEnum {
    PUBLISH("publish"),
    
    REGISTER("register"),
    
    HIDE("hide");

    private String value;

    EventEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventEnum fromValue(String value) {
      for (EventEnum b : EventEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT = "event";
  private EventEnum event;

  public static final String JSON_PROPERTY_IDENTIFIERS = "identifiers";
  private List<DoiDataAttributesIdentifiers> identifiers = null;

  public static final String JSON_PROPERTY_CREATORS = "creators";
  private List<DoiDataAttributesCreators> creators = null;

  public static final String JSON_PROPERTY_TITLES = "titles";
  private List<DoiDataAttributesTitles> titles = null;

  public static final String JSON_PROPERTY_PUBLISHER = "publisher";
  private String publisher;

  public static final String JSON_PROPERTY_CONTAINER = "container";
  private DoiDataAttributesContainer container;

  public static final String JSON_PROPERTY_PUBLICATION_YEAR = "publicationYear";
  private BigDecimal publicationYear;

  public static final String JSON_PROPERTY_SUBJECTS = "subjects";
  private List<DoiDataAttributesSubjects> subjects = null;

  public static final String JSON_PROPERTY_CONTRIBUTORS = "contributors";
  private List<DoiDataAttributesContributors> contributors = null;

  public static final String JSON_PROPERTY_DATES = "dates";
  private List<DoiDataAttributesDates> dates = null;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_TYPES = "types";
  private DoiDataAttributesTypes types;

  public static final String JSON_PROPERTY_RELATED_IDENTIFIERS = "relatedIdentifiers";
  private List<DoiDataAttributesRelatedIdentifiers> relatedIdentifiers = null;

  public static final String JSON_PROPERTY_SIZES = "sizes";
  private List<String> sizes = null;

  public static final String JSON_PROPERTY_FORMATS = "formats";
  private List<String> formats = null;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_RIGHTS_LIST = "rightsList";
  private List<DoiDataAttributesRightsList> rightsList = null;

  public static final String JSON_PROPERTY_DESCRIPTIONS = "descriptions";
  private List<DoiDataAttributesDescriptions> descriptions = null;

  public static final String JSON_PROPERTY_GEO_LOCATIONS = "geoLocations";
  private List<DoiDataAttributesGeoLocations> geoLocations = null;

  public static final String JSON_PROPERTY_FUNDING_REFERENCES = "fundingReferences";
  private List<DoiDataAttributesFundingReferences> fundingReferences = null;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_CONTENT_URL = "contentUrl";
  private List<String> contentUrl = null;

  public static final String JSON_PROPERTY_METADATA_VERSION = "metadataVersion";
  private BigDecimal metadataVersion;

  public static final String JSON_PROPERTY_SCHEMA_VERSION = "schemaVersion";
  private String schemaVersion;

  public static final String JSON_PROPERTY_SOURCE = "source";
  private String source;

  public static final String JSON_PROPERTY_IS_ACTIVE = "isActive";
  private Boolean isActive;

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_LANDING_PAGE = "landingPage";
  private DoiDataAttributesLandingPage landingPage;

  public static final String JSON_PROPERTY_CREATED = "created";
  private String created;

  public static final String JSON_PROPERTY_REGISTERED = "registered";
  private String registered;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  private String updated;


  public DoiDataAttributes doi(String doi) {
    
    this.doi = doi;
    return this;
  }

   /**
   * Get doi
   * @return doi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DOI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoi() {
    return doi;
  }


  public void setDoi(String doi) {
    this.doi = doi;
  }


  public DoiDataAttributes prefix(String prefix) {
    
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrefix() {
    return prefix;
  }


  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }


  public DoiDataAttributes suffix(String suffix) {
    
    this.suffix = suffix;
    return this;
  }

   /**
   * Get suffix
   * @return suffix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUFFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSuffix() {
    return suffix;
  }


  public void setSuffix(String suffix) {
    this.suffix = suffix;
  }


  public DoiDataAttributes event(EventEnum event) {
    
    this.event = event;
    return this;
  }

   /**
   * Can be set to trigger a DOI state change.
   * @return event
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Can be set to trigger a DOI state change.")
  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventEnum getEvent() {
    return event;
  }


  public void setEvent(EventEnum event) {
    this.event = event;
  }


  public DoiDataAttributes identifiers(List<DoiDataAttributesIdentifiers> identifiers) {
    
    this.identifiers = identifiers;
    return this;
  }

  public DoiDataAttributes addIdentifiersItem(DoiDataAttributesIdentifiers identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

   /**
   * Get identifiers
   * @return identifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesIdentifiers> getIdentifiers() {
    return identifiers;
  }


  public void setIdentifiers(List<DoiDataAttributesIdentifiers> identifiers) {
    this.identifiers = identifiers;
  }


  public DoiDataAttributes creators(List<DoiDataAttributesCreators> creators) {
    
    this.creators = creators;
    return this;
  }

  public DoiDataAttributes addCreatorsItem(DoiDataAttributesCreators creatorsItem) {
    if (this.creators == null) {
      this.creators = new ArrayList<>();
    }
    this.creators.add(creatorsItem);
    return this;
  }

   /**
   * Get creators
   * @return creators
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesCreators> getCreators() {
    return creators;
  }


  public void setCreators(List<DoiDataAttributesCreators> creators) {
    this.creators = creators;
  }


  public DoiDataAttributes titles(List<DoiDataAttributesTitles> titles) {
    
    this.titles = titles;
    return this;
  }

  public DoiDataAttributes addTitlesItem(DoiDataAttributesTitles titlesItem) {
    if (this.titles == null) {
      this.titles = new ArrayList<>();
    }
    this.titles.add(titlesItem);
    return this;
  }

   /**
   * Get titles
   * @return titles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TITLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesTitles> getTitles() {
    return titles;
  }


  public void setTitles(List<DoiDataAttributesTitles> titles) {
    this.titles = titles;
  }


  public DoiDataAttributes publisher(String publisher) {
    
    this.publisher = publisher;
    return this;
  }

   /**
   * Get publisher
   * @return publisher
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PUBLISHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublisher() {
    return publisher;
  }


  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }


  public DoiDataAttributes container(DoiDataAttributesContainer container) {
    
    this.container = container;
    return this;
  }

   /**
   * Get container
   * @return container
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTAINER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DoiDataAttributesContainer getContainer() {
    return container;
  }


  public void setContainer(DoiDataAttributesContainer container) {
    this.container = container;
  }


  public DoiDataAttributes publicationYear(BigDecimal publicationYear) {
    
    this.publicationYear = publicationYear;
    return this;
  }

   /**
   * Get publicationYear
   * @return publicationYear
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PUBLICATION_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPublicationYear() {
    return publicationYear;
  }


  public void setPublicationYear(BigDecimal publicationYear) {
    this.publicationYear = publicationYear;
  }


  public DoiDataAttributes subjects(List<DoiDataAttributesSubjects> subjects) {
    
    this.subjects = subjects;
    return this;
  }

  public DoiDataAttributes addSubjectsItem(DoiDataAttributesSubjects subjectsItem) {
    if (this.subjects == null) {
      this.subjects = new ArrayList<>();
    }
    this.subjects.add(subjectsItem);
    return this;
  }

   /**
   * Get subjects
   * @return subjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesSubjects> getSubjects() {
    return subjects;
  }


  public void setSubjects(List<DoiDataAttributesSubjects> subjects) {
    this.subjects = subjects;
  }


  public DoiDataAttributes contributors(List<DoiDataAttributesContributors> contributors) {
    
    this.contributors = contributors;
    return this;
  }

  public DoiDataAttributes addContributorsItem(DoiDataAttributesContributors contributorsItem) {
    if (this.contributors == null) {
      this.contributors = new ArrayList<>();
    }
    this.contributors.add(contributorsItem);
    return this;
  }

   /**
   * Get contributors
   * @return contributors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTRIBUTORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesContributors> getContributors() {
    return contributors;
  }


  public void setContributors(List<DoiDataAttributesContributors> contributors) {
    this.contributors = contributors;
  }


  public DoiDataAttributes dates(List<DoiDataAttributesDates> dates) {
    
    this.dates = dates;
    return this;
  }

  public DoiDataAttributes addDatesItem(DoiDataAttributesDates datesItem) {
    if (this.dates == null) {
      this.dates = new ArrayList<>();
    }
    this.dates.add(datesItem);
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesDates> getDates() {
    return dates;
  }


  public void setDates(List<DoiDataAttributesDates> dates) {
    this.dates = dates;
  }


  public DoiDataAttributes language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public DoiDataAttributes types(DoiDataAttributesTypes types) {
    
    this.types = types;
    return this;
  }

   /**
   * Get types
   * @return types
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DoiDataAttributesTypes getTypes() {
    return types;
  }


  public void setTypes(DoiDataAttributesTypes types) {
    this.types = types;
  }


  public DoiDataAttributes relatedIdentifiers(List<DoiDataAttributesRelatedIdentifiers> relatedIdentifiers) {
    
    this.relatedIdentifiers = relatedIdentifiers;
    return this;
  }

  public DoiDataAttributes addRelatedIdentifiersItem(DoiDataAttributesRelatedIdentifiers relatedIdentifiersItem) {
    if (this.relatedIdentifiers == null) {
      this.relatedIdentifiers = new ArrayList<>();
    }
    this.relatedIdentifiers.add(relatedIdentifiersItem);
    return this;
  }

   /**
   * Get relatedIdentifiers
   * @return relatedIdentifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELATED_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesRelatedIdentifiers> getRelatedIdentifiers() {
    return relatedIdentifiers;
  }


  public void setRelatedIdentifiers(List<DoiDataAttributesRelatedIdentifiers> relatedIdentifiers) {
    this.relatedIdentifiers = relatedIdentifiers;
  }


  public DoiDataAttributes sizes(List<String> sizes) {
    
    this.sizes = sizes;
    return this;
  }

  public DoiDataAttributes addSizesItem(String sizesItem) {
    if (this.sizes == null) {
      this.sizes = new ArrayList<>();
    }
    this.sizes.add(sizesItem);
    return this;
  }

   /**
   * Get sizes
   * @return sizes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIZES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSizes() {
    return sizes;
  }


  public void setSizes(List<String> sizes) {
    this.sizes = sizes;
  }


  public DoiDataAttributes formats(List<String> formats) {
    
    this.formats = formats;
    return this;
  }

  public DoiDataAttributes addFormatsItem(String formatsItem) {
    if (this.formats == null) {
      this.formats = new ArrayList<>();
    }
    this.formats.add(formatsItem);
    return this;
  }

   /**
   * Get formats
   * @return formats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getFormats() {
    return formats;
  }


  public void setFormats(List<String> formats) {
    this.formats = formats;
  }


  public DoiDataAttributes version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public DoiDataAttributes rightsList(List<DoiDataAttributesRightsList> rightsList) {
    
    this.rightsList = rightsList;
    return this;
  }

  public DoiDataAttributes addRightsListItem(DoiDataAttributesRightsList rightsListItem) {
    if (this.rightsList == null) {
      this.rightsList = new ArrayList<>();
    }
    this.rightsList.add(rightsListItem);
    return this;
  }

   /**
   * Get rightsList
   * @return rightsList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RIGHTS_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesRightsList> getRightsList() {
    return rightsList;
  }


  public void setRightsList(List<DoiDataAttributesRightsList> rightsList) {
    this.rightsList = rightsList;
  }


  public DoiDataAttributes descriptions(List<DoiDataAttributesDescriptions> descriptions) {
    
    this.descriptions = descriptions;
    return this;
  }

  public DoiDataAttributes addDescriptionsItem(DoiDataAttributesDescriptions descriptionsItem) {
    if (this.descriptions == null) {
      this.descriptions = new ArrayList<>();
    }
    this.descriptions.add(descriptionsItem);
    return this;
  }

   /**
   * Get descriptions
   * @return descriptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesDescriptions> getDescriptions() {
    return descriptions;
  }


  public void setDescriptions(List<DoiDataAttributesDescriptions> descriptions) {
    this.descriptions = descriptions;
  }


  public DoiDataAttributes geoLocations(List<DoiDataAttributesGeoLocations> geoLocations) {
    
    this.geoLocations = geoLocations;
    return this;
  }

  public DoiDataAttributes addGeoLocationsItem(DoiDataAttributesGeoLocations geoLocationsItem) {
    if (this.geoLocations == null) {
      this.geoLocations = new ArrayList<>();
    }
    this.geoLocations.add(geoLocationsItem);
    return this;
  }

   /**
   * Get geoLocations
   * @return geoLocations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GEO_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesGeoLocations> getGeoLocations() {
    return geoLocations;
  }


  public void setGeoLocations(List<DoiDataAttributesGeoLocations> geoLocations) {
    this.geoLocations = geoLocations;
  }


  public DoiDataAttributes fundingReferences(List<DoiDataAttributesFundingReferences> fundingReferences) {
    
    this.fundingReferences = fundingReferences;
    return this;
  }

  public DoiDataAttributes addFundingReferencesItem(DoiDataAttributesFundingReferences fundingReferencesItem) {
    if (this.fundingReferences == null) {
      this.fundingReferences = new ArrayList<>();
    }
    this.fundingReferences.add(fundingReferencesItem);
    return this;
  }

   /**
   * Get fundingReferences
   * @return fundingReferences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FUNDING_REFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DoiDataAttributesFundingReferences> getFundingReferences() {
    return fundingReferences;
  }


  public void setFundingReferences(List<DoiDataAttributesFundingReferences> fundingReferences) {
    this.fundingReferences = fundingReferences;
  }


  public DoiDataAttributes url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public DoiDataAttributes contentUrl(List<String> contentUrl) {
    
    this.contentUrl = contentUrl;
    return this;
  }

  public DoiDataAttributes addContentUrlItem(String contentUrlItem) {
    if (this.contentUrl == null) {
      this.contentUrl = new ArrayList<>();
    }
    this.contentUrl.add(contentUrlItem);
    return this;
  }

   /**
   * Get contentUrl
   * @return contentUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getContentUrl() {
    return contentUrl;
  }


  public void setContentUrl(List<String> contentUrl) {
    this.contentUrl = contentUrl;
  }


  public DoiDataAttributes metadataVersion(BigDecimal metadataVersion) {
    
    this.metadataVersion = metadataVersion;
    return this;
  }

   /**
   * Get metadataVersion
   * @return metadataVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getMetadataVersion() {
    return metadataVersion;
  }


  public void setMetadataVersion(BigDecimal metadataVersion) {
    this.metadataVersion = metadataVersion;
  }


  public DoiDataAttributes schemaVersion(String schemaVersion) {
    
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEMA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaVersion() {
    return schemaVersion;
  }


  public void setSchemaVersion(String schemaVersion) {
    this.schemaVersion = schemaVersion;
  }


  public DoiDataAttributes source(String source) {
    
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  public void setSource(String source) {
    this.source = source;
  }


  public DoiDataAttributes isActive(Boolean isActive) {
    
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsActive() {
    return isActive;
  }


  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }


   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }




  public DoiDataAttributes reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    this.reason = reason;
  }


  public DoiDataAttributes landingPage(DoiDataAttributesLandingPage landingPage) {
    
    this.landingPage = landingPage;
    return this;
  }

   /**
   * Get landingPage
   * @return landingPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LANDING_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DoiDataAttributesLandingPage getLandingPage() {
    return landingPage;
  }


  public void setLandingPage(DoiDataAttributesLandingPage landingPage) {
    this.landingPage = landingPage;
  }


   /**
   * Get created
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }




   /**
   * Get registered
   * @return registered
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REGISTERED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegistered() {
    return registered;
  }




   /**
   * Get updated
   * @return updated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdated() {
    return updated;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoiDataAttributes doiDataAttributes = (DoiDataAttributes) o;
    return Objects.equals(this.doi, doiDataAttributes.doi) &&
        Objects.equals(this.prefix, doiDataAttributes.prefix) &&
        Objects.equals(this.suffix, doiDataAttributes.suffix) &&
        Objects.equals(this.event, doiDataAttributes.event) &&
        Objects.equals(this.identifiers, doiDataAttributes.identifiers) &&
        Objects.equals(this.creators, doiDataAttributes.creators) &&
        Objects.equals(this.titles, doiDataAttributes.titles) &&
        Objects.equals(this.publisher, doiDataAttributes.publisher) &&
        Objects.equals(this.container, doiDataAttributes.container) &&
        Objects.equals(this.publicationYear, doiDataAttributes.publicationYear) &&
        Objects.equals(this.subjects, doiDataAttributes.subjects) &&
        Objects.equals(this.contributors, doiDataAttributes.contributors) &&
        Objects.equals(this.dates, doiDataAttributes.dates) &&
        Objects.equals(this.language, doiDataAttributes.language) &&
        Objects.equals(this.types, doiDataAttributes.types) &&
        Objects.equals(this.relatedIdentifiers, doiDataAttributes.relatedIdentifiers) &&
        Objects.equals(this.sizes, doiDataAttributes.sizes) &&
        Objects.equals(this.formats, doiDataAttributes.formats) &&
        Objects.equals(this.version, doiDataAttributes.version) &&
        Objects.equals(this.rightsList, doiDataAttributes.rightsList) &&
        Objects.equals(this.descriptions, doiDataAttributes.descriptions) &&
        Objects.equals(this.geoLocations, doiDataAttributes.geoLocations) &&
        Objects.equals(this.fundingReferences, doiDataAttributes.fundingReferences) &&
        Objects.equals(this.url, doiDataAttributes.url) &&
        Objects.equals(this.contentUrl, doiDataAttributes.contentUrl) &&
        Objects.equals(this.metadataVersion, doiDataAttributes.metadataVersion) &&
        Objects.equals(this.schemaVersion, doiDataAttributes.schemaVersion) &&
        Objects.equals(this.source, doiDataAttributes.source) &&
        Objects.equals(this.isActive, doiDataAttributes.isActive) &&
        Objects.equals(this.state, doiDataAttributes.state) &&
        Objects.equals(this.reason, doiDataAttributes.reason) &&
        Objects.equals(this.landingPage, doiDataAttributes.landingPage) &&
        Objects.equals(this.created, doiDataAttributes.created) &&
        Objects.equals(this.registered, doiDataAttributes.registered) &&
        Objects.equals(this.updated, doiDataAttributes.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(doi, prefix, suffix, event, identifiers, creators, titles, publisher, container, publicationYear, subjects, contributors, dates, language, types, relatedIdentifiers, sizes, formats, version, rightsList, descriptions, geoLocations, fundingReferences, url, contentUrl, metadataVersion, schemaVersion, source, isActive, state, reason, landingPage, created, registered, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoiDataAttributes {\n");
    sb.append("    doi: ").append(toIndentedString(doi)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    suffix: ").append(toIndentedString(suffix)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    creators: ").append(toIndentedString(creators)).append("\n");
    sb.append("    titles: ").append(toIndentedString(titles)).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    publicationYear: ").append(toIndentedString(publicationYear)).append("\n");
    sb.append("    subjects: ").append(toIndentedString(subjects)).append("\n");
    sb.append("    contributors: ").append(toIndentedString(contributors)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    relatedIdentifiers: ").append(toIndentedString(relatedIdentifiers)).append("\n");
    sb.append("    sizes: ").append(toIndentedString(sizes)).append("\n");
    sb.append("    formats: ").append(toIndentedString(formats)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    rightsList: ").append(toIndentedString(rightsList)).append("\n");
    sb.append("    descriptions: ").append(toIndentedString(descriptions)).append("\n");
    sb.append("    geoLocations: ").append(toIndentedString(geoLocations)).append("\n");
    sb.append("    fundingReferences: ").append(toIndentedString(fundingReferences)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    contentUrl: ").append(toIndentedString(contentUrl)).append("\n");
    sb.append("    metadataVersion: ").append(toIndentedString(metadataVersion)).append("\n");
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    landingPage: ").append(toIndentedString(landingPage)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    registered: ").append(toIndentedString(registered)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

