/*
 * REST API
 * The REST API is used for all API interactions with DataCite services.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@datacite.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.unit.nva.doi.datacite.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ReportData
 */
@JsonPropertyOrder({
  ReportData.JSON_PROPERTY_ID,
  ReportData.JSON_PROPERTY_REPORT_NAME,
  ReportData.JSON_PROPERTY_REPORT_ID,
  ReportData.JSON_PROPERTY_RELEASE,
  ReportData.JSON_PROPERTY_CREATED,
  ReportData.JSON_PROPERTY_CREATED_BY,
  ReportData.JSON_PROPERTY_REPORT_FILTERS,
  ReportData.JSON_PROPERTY_REPORT_ATTRIBUTES,
  ReportData.JSON_PROPERTY_REPORTING_PERIOD,
  ReportData.JSON_PROPERTY_REPORT_DATASETS
})

public class ReportData {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_REPORT_NAME = "report-name";
  private String reportName;

  public static final String JSON_PROPERTY_REPORT_ID = "report-id";
  private String reportId;

  public static final String JSON_PROPERTY_RELEASE = "release";
  private String release;

  public static final String JSON_PROPERTY_CREATED = "created";
  private String created;

  public static final String JSON_PROPERTY_CREATED_BY = "created-by";
  private String createdBy;

  public static final String JSON_PROPERTY_REPORT_FILTERS = "report-filters";
  private String reportFilters;

  public static final String JSON_PROPERTY_REPORT_ATTRIBUTES = "report-attributes";
  private String reportAttributes;

  public static final String JSON_PROPERTY_REPORTING_PERIOD = "reporting-period";
  private String reportingPeriod;

  public static final String JSON_PROPERTY_REPORT_DATASETS = "report-datasets";
  private String reportDatasets;


  public ReportData id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0000-0000-0000-0000", value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ReportData reportName(String reportName) {
    
    this.reportName = reportName;
    return this;
  }

   /**
   * The long name of the report.
   * @return reportName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Dataset Report", value = "The long name of the report.")
  @JsonProperty(JSON_PROPERTY_REPORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportName() {
    return reportName;
  }


  public void setReportName(String reportName) {
    this.reportName = reportName;
  }


  public ReportData reportId(String reportId) {
    
    this.reportId = reportId;
    return this;
  }

   /**
   * The report ID or code or shortname. Typically this will be the same code provided in the Report parameter of the request.
   * @return reportId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DSR", value = "The report ID or code or shortname. Typically this will be the same code provided in the Report parameter of the request.")
  @JsonProperty(JSON_PROPERTY_REPORT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportId() {
    return reportId;
  }


  public void setReportId(String reportId) {
    this.reportId = reportId;
  }


  public ReportData release(String release) {
    
    this.release = release;
    return this;
  }

   /**
   * The release or version of the report.
   * @return release
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "RD1", value = "The release or version of the report.")
  @JsonProperty(JSON_PROPERTY_RELEASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelease() {
    return release;
  }


  public void setRelease(String release) {
    this.release = release;
  }


  public ReportData created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * Time the report was prepared. Format as defined by date-time - RFC3339
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2016-09-08T22:47:31Z", value = "Time the report was prepared. Format as defined by date-time - RFC3339")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }


  public void setCreated(String created) {
    this.created = created;
  }


  public ReportData createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Name of the organization producing the report.
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DataONE", value = "Name of the organization producing the report.")
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public ReportData reportFilters(String reportFilters) {
    
    this.reportFilters = reportFilters;
    return this;
  }

   /**
   * Zero or more report filters used for this report. Typically reflect filters provided on the Request. Filters limit the data to be reported on.
   * @return reportFilters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Zero or more report filters used for this report. Typically reflect filters provided on the Request. Filters limit the data to be reported on.")
  @JsonProperty(JSON_PROPERTY_REPORT_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportFilters() {
    return reportFilters;
  }


  public void setReportFilters(String reportFilters) {
    this.reportFilters = reportFilters;
  }


  public ReportData reportAttributes(String reportAttributes) {
    
    this.reportAttributes = reportAttributes;
    return this;
  }

   /**
   * Zero or more additional attributes applied to the report. Attributes inform the level of detail in the report.
   * @return reportAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Zero or more additional attributes applied to the report. Attributes inform the level of detail in the report.")
  @JsonProperty(JSON_PROPERTY_REPORT_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportAttributes() {
    return reportAttributes;
  }


  public void setReportAttributes(String reportAttributes) {
    this.reportAttributes = reportAttributes;
  }


  public ReportData reportingPeriod(String reportingPeriod) {
    
    this.reportingPeriod = reportingPeriod;
    return this;
  }

   /**
   * Time the report was prepared.
   * @return reportingPeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Time the report was prepared.")
  @JsonProperty(JSON_PROPERTY_REPORTING_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportingPeriod() {
    return reportingPeriod;
  }


  public void setReportingPeriod(String reportingPeriod) {
    this.reportingPeriod = reportingPeriod;
  }


  public ReportData reportDatasets(String reportDatasets) {
    
    this.reportDatasets = reportDatasets;
    return this;
  }

   /**
   * Defines the output for the Report_Datasets being returned in a Dataset Report. Collection of datasets from the report.
   * @return reportDatasets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines the output for the Report_Datasets being returned in a Dataset Report. Collection of datasets from the report.")
  @JsonProperty(JSON_PROPERTY_REPORT_DATASETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportDatasets() {
    return reportDatasets;
  }


  public void setReportDatasets(String reportDatasets) {
    this.reportDatasets = reportDatasets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportData reportData = (ReportData) o;
    return Objects.equals(this.id, reportData.id) &&
        Objects.equals(this.reportName, reportData.reportName) &&
        Objects.equals(this.reportId, reportData.reportId) &&
        Objects.equals(this.release, reportData.release) &&
        Objects.equals(this.created, reportData.created) &&
        Objects.equals(this.createdBy, reportData.createdBy) &&
        Objects.equals(this.reportFilters, reportData.reportFilters) &&
        Objects.equals(this.reportAttributes, reportData.reportAttributes) &&
        Objects.equals(this.reportingPeriod, reportData.reportingPeriod) &&
        Objects.equals(this.reportDatasets, reportData.reportDatasets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, reportName, reportId, release, created, createdBy, reportFilters, reportAttributes, reportingPeriod, reportDatasets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reportName: ").append(toIndentedString(reportName)).append("\n");
    sb.append("    reportId: ").append(toIndentedString(reportId)).append("\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    reportFilters: ").append(toIndentedString(reportFilters)).append("\n");
    sb.append("    reportAttributes: ").append(toIndentedString(reportAttributes)).append("\n");
    sb.append("    reportingPeriod: ").append(toIndentedString(reportingPeriod)).append("\n");
    sb.append("    reportDatasets: ").append(toIndentedString(reportDatasets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

